### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by MS71** [micro-ROS/micro_ros_espidf_component#1]
Hi,
suddenly, i get a build issue with this component.

My build commands:
rm -rf build components/micro-ROS/micro_ros_* components/micro-ROS/esp32_toolchain.cmake components/micro-ROS/include/ components/micro-ROS/*.a
export IDF_PATH=/home/maik/workspace/esp32/stable
source /opt/ros/foxy/setup.sh
. $IDF_PATH/export.sh
echo $IDF_PATH
#idf.py menuconfig
idf.py -v build

...
Summary: 22 packages finished [22.9s]
  1 package failed: builtin_interfaces
  4 packages aborted: lifecycle_msgs rmw_microxrcedds std_srvs unique_identifier_msgs
  23 packages had stderr output: builtin_interfaces lifecycle_msgs microcdr microxrcedds_client rcutils rmw rmw_implementation_cmake rmw_microxrcedds rosidl_adapter rosidl_cmake 
...

Any hint howto solve this issue?

[build.txt](https://github.com/micro-ROS/micro_ros_espidf_component/files/5213818/build.txt)

**Comment by pablogs9** [comment]
Hello @MS71, I guess that this is an error about mixing two different builds. Anyways remember that this is experimental and we are polishing the integration.

Which IDF version are you using? Does it appear when you follow the steps in a clean environment? Have you tried to delete also the IDF build folder?

It seems that CMake is not finding the correct version of the serialization library (Micro-CDR), could you provide some replication steps to reproduce this from scratch?

Thanks

**Comment by MS71** [comment]
Hi,

Which IDF version are you using? 
I checked with ESP IDF v4.1 and v4.0.1.

Does it appear when you follow the steps in a clean environment? 
Yes

Have you tried to delete also the IDF build folder?
=> rm -rf build components/micro-ROS/micro_ros_* components/micro-ROS/esp32_toolchain.cmake components/micro-ROS/include/ 
Also, with clean checkout from your gitrep.

So, Yes

>could you provide some replication steps to reproduce this from scratch?
rm -rf build components/micro-ROS/micro_ros_* components/micro-ROS/esp32_toolchain.cmake components/micro-ROS/include/ components/micro-ROS/*.a
... or a clean clone of your gitrep.

export IDF_PATH=/home/maik/workspace/esp32/esp-idf-v4.1
source /opt/ros/foxy/setup.sh
. $IDF_PATH/export.sh
echo $IDF_PATH
idf.py menuconfig
idf.py -v build

**Comment by pablogs9** [comment]
Well, you are having troubles with `fastcdr` this is not a package downloaded by this module [check this](https://github.com/micro-ROS/micro_ros_espidf_component/blob/fb22d6fa083d8aafdb2bbb7ed8384ce5838bb00c/components/micro-ROS/libmicroros.mk#L46).

Why are you sourcing the ROS 2 foxy installation?

For me it works as expected in a clean IDF environment, with no ROS 2 Foxy sourcing, you can check my test here:

https://asciinema.org/a/GGaO235tw7zc0MDiOhgUyT0ZT

**Comment by MS71** [comment]
Hi,
yes you are right. Without "source /opt/ros/foxy/setup.sh", all fine.
Sorry about this issue.

**Comment by pablogs9** [comment]
Don't you worry, don't hesitate to ask, and please provide feedback! Thanks!
