### ISSUE TITLE
Directory structure for micro_ros_espidf_component

### ISSUE THREAD

**Issue by dsryzhov** [micro-ROS/micro_ros_espidf_component#10]
It's my proposal for changinf directory structure for this repository  
to make  it compatible with esp-idf component.
It will make it possible to use Micro-ROS esp idf component  in stadard way by simple 
cloning it to components directory of any project.

In the current version this repository contains example application that use micro-ros-espidf-component. 
It can't be used in other applications by simply cloning it.
Currently this repository could be named as micro_ros_espidf_component_example. 

I've made an example with new directory structure 
https://github.com/dsryzhov/micro_ros_espidf_component/blob/feature/clear-idf-component/README.md

In new structure component files are on the root directory of repository.
Example application files are in the example\int32_publisher directory.

I already use my repository with a new directory structure to add Micro-ROS component to different projects.

**Comment by pablogs9** [comment]
Closing and moving discussion to: https://github.com/micro-ROS/micro_ros_espidf_component/pull/11
