### ISSUE TITLE
why is the rccheck deleting the task if it doesn't initialize or if it doesn't see the agent?

### ISSUE THREAD

**Issue by wegunterjr** [micro-ROS/micro_ros_espidf_component#114]
## Issue template

- Hardware description: esp32
- RTOS:  FreeRTOS
- Installation type: esp idf component
- Version or commit hash: galactic espidf component/galactic micro ros agent docker

#### Steps to reproduce the issue
Following example int32_publisher or other micro_ros programs running on esp32 with freertos, the example shows to use RCCHECK.
Sometimes there might be issues with the network or maybe micro_ros_agent is restarted, etc, but the example shows that if during initialization of the esp32 program, the agent is not available it aborts and deletes the task. Does it have to be so final? 
Was this just to make it easy during initial bring up and getting someone an understanding?  or was there another reason I am not seeing?

Thanks!!

**Comment by pablogs9** [comment]
We are just checking if the initialization is done properly and just crashing the app if something fails. Just example code. You can implement your own logic for handling errors.
