### ISSUE TITLE
Int32_publisher example fails at create init_options

### ISSUE THREAD

**Issue by AntumArk** [micro-ROS/micro_ros_espidf_component#132]
## Int32_publisher example fails at create init_options

- Hardware description: **ESP32 devkitCv4, Host Windows 10 AMD Ryzen, Ubuntu 20.04.4 VM.**
- RTOS: Just running default example
- Installation type: idf.py
- Version or commit hash: Galactic https://github.com/micro-ROS/micro_ros_espidf_component/commit/eb6b9b7545ceb8da05eb99555a27e1f355f77387 foxy https://github.com/micro-ROS/micro_ros_espidf_component/commit/abf1c8b863539599f462e8cade70aab9ad74db19

#### Steps to reproduce the issue

1.  Follow espressif tutorial on how to install esp-idf on linux (In my case, Ubuntu VM). [ESP-IDF install turorial](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/index.html#get-started-get-esp-idf) . And run _hello world_ example to verify that your device is configured correctly.
2. Create _components_ directory and clone this repository either galactic or foxy branches.
3. Follow [this repo example](https://github.com/micro-ROS/micro_ros_espidf_component/tree/foxy#readme) to menuconfig
4. Change wifi credentials and RosConfig to have your host (Windows 10) IP . 
5. Continue following example
6. Run docker container on host PC  just like in example. 

The issue can be replicated both running in foxy and galactic builds. 

#### Expected behavior

1. Example builds, flashes, and runs until the point where connection to the ros-agent is needed

#### Actual behavior

1. ESP32 connects to Wifi
2. Starts initializing ros
3. and halts at 
![image](https://user-images.githubusercontent.com/23199497/155857624-c5f633ae-f479-4366-a825-923929cb0144.png)

https://github.com/micro-ROS/micro_ros_espidf_component/blob/abf1c8b863539599f462e8cade70aab9ad74db19/examples/int32_publisher/main/main.c#L48
both in galactic and foxy.

#### Additional information

I also tried to flash this on my other ESP32 which is as I can remember devkitv1, but It had a lot of stuff written inside so some configurations may have been lost and now I can't flash to it at all :) . If needed I have multiple ESP32 lying around so i can test on these too.

**Comment by pablogs9** [comment]
Could you paste here the output of the micro-ROS Agent with flag `-v6`? It seems that you have a network problem and the client (ESP32) is not reaching the micro-ROS Agent.

**Comment by AntumArk** [comment]
C:\Users\MSI>docker run -it --rm --net=host microros/micro-ros-agent:foxy udp4 --port 8888 -v6
[1646031030.915633] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 8888
[1646031030.916791] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6

That is it

**Comment by pablogs9** [comment]
Your client is not reaching the agent, is the agent's IP configured well on the micro-ROS client side? Are both in the same network? Can you ping from the agent machine the client's IP?

**Comment by AntumArk** [comment]
> Your client is not reaching the agent, is the agent's IP configured well on the micro-ROS client side? Are both in the same network? Can you ping from the agent machine the client's IP?

Agent machine - > client IP  Ping successful
VM - > Agent machine ping also successful
![image](https://user-images.githubusercontent.com/23199497/155940543-35f96793-f5e0-4cc1-89f2-70c0a93a281d.png)
![image](https://user-images.githubusercontent.com/23199497/155940640-0322bb57-b0cc-4056-865f-6962a7085969.png)
Yes they are on the same network.

**Comment by pablogs9** [comment]
Can you ping from the virtual machine to the ESP32?

**Comment by AntumArk** [comment]
Yes, it pings.

**Comment by pablogs9** [comment]
Could you test if a native installation of the Agent in a Linux-based system works properly?

**Comment by AntumArk** [comment]
I get the same output 
![image](https://user-images.githubusercontent.com/23199497/155946962-8e248698-c5c2-4593-99a0-129f73e4fdd3.png)
But I am not sure if I should change microros Ip. Shouldn't VM IP be the same as host PC?

**Comment by pablogs9** [comment]
I'm not aware of your VM networking configuration, but the micro-ROS client should be able to connect to the UDP port opened on the agent side. In any case, you can try a basic UDP socket example in order to ensure this connectivity before using micro-ROS.

**Comment by AntumArk** [comment]
So I need to test
UDP Server <-> ESP32 Running UDP Socket example ? I am kind of bad at networking, so it is slighly confusing.

**Comment by pablogs9** [comment]
Yes, basically you need to verify that your ESP32 connected to your network is able to connect to a UDP socket in the same place where you are going to run the agent.

**Comment by AntumArk** [comment]
It seems that I am unable to connect to 8888 port even from anything apart localhost. I tried also using RPI to test UDP to AgentPC with no response. Although ping to xx.194 worked.
For UDP server I used 
` import socket 
localIP     = "192.168.1.194"

localPort   = 8888

bufferSize  = 1024 

msgFromServer       = "Hello UDP Client"

bytesToSend         = str.encode(msgFromServer) 

UDPServerSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM) 

UDPServerSocket.bind((localIP, localPort)) 

print("UDP server up and listening") 

while(True):   
    bytesAddressPair = UDPServerSocket.recvfrom(bufferSize)

    message = bytesAddressPair[0]

    address = bytesAddressPair[1]
    print("Sending meessag")
    UDPServerSocket.sendto(bytesToSend, address)
    clientMsg = "Message from Client:{}".format(message)
    clientIP  = "Client IP Address:{}".format(address)    
    print(clientMsg)
    print(clientIP)   

    # Sending a reply to client

    UDPServerSocket.sendto(bytesToSend, address)`

I will investigate this later this day.

**Comment by AntumArk** [comment]
Ok, so . Trying to reduce variables... 

Who can send and receive packets when ESP32 is acting as UDP server:
- rpi
- HostPC (Windows)

![image](https://user-images.githubusercontent.com/23199497/156017628-53aeb04a-8de7-4f75-a8db-934ed3a79bdb.png)

Now switching to ESP32 as UDP client and trying to connect to different server hosts.

**Comment by AntumArk** [comment]
So ESP32, HostPC ,VM Client, -> RPI running nodered UDB server - successful  Send transfer 
![image](https://user-images.githubusercontent.com/23199497/156024638-026f5dc3-8f89-42ca-adaf-5d1e911b3d13.png)
Well, at least UDP seems to be working. What changed is that I had to unblock UDP in my firewall for specific devices. 

So next is running ros agent? @pablogs9

**Comment by AntumArk** [comment]
microrosagent does not support ARM . 
![image](https://user-images.githubusercontent.com/23199497/156026821-63861df1-7701-4ea1-aee5-eaf1040554ad.png)

**Comment by pablogs9** [comment]
micro-ROS agent does support ARM, just follow the instructions for building it: https://github.com/micro-ROS/micro_ros_setup#building-micro-ros-agent

**Comment by mmigliavacca** [comment]
I'm facing the same issue, with the int32_publisher demo failing at line 49 which is:
`RCCHECK(rmw_uros_options_set_udp_address(CONFIG_MICRO_ROS_AGENT_IP, CONFIG_MICRO_ROS_AGENT_PORT, rmw_options));
`

The strange thing is that this demo, as well as the firmware we developed, was running until last week. Agent address and port are correct.
It is not a firewall issue as the agent receives the data if I run a simple UDP client on the ESP32:
![Screenshot from 2022-03-02 16-33-15](https://user-images.githubusercontent.com/18289376/156393918-c4f10e3b-199f-48d5-9061-6dc5fdf4c742.png)

While nothing is received when running the demo. Any suggestion to debug this kind of issues?

**Comment by pablogs9** [comment]
@mmigliavacca Which is the return code of `rmw_uros_options_set_udp_address()`?

**Comment by pablogs9** [comment]
@AntumArk did you solve your communication issue?

**Comment by AntumArk** [comment]
Unfortunatelly no, I tried to eliminate firewall issues by running agent on RPi3 , but apperenlty I also need to compile from source ros2, so I got stuck there. Although I did not try to send Udp packets to running Ros agent as @mmigliavacca did. I will try it out.

**Comment by pablogs9** [comment]
@AntumArk if you use ubuntu in the RPi 3 you can install ROS 2 from `apt`

**Comment by mmigliavacca** [comment]
@pablogs9, thanks for the super-quick reply.
- the return code is 11, which I see is `RMW_RET_INVALID_ARGUMENT`
- the code is the int32_publisher example, untouched
- `CONFIG_MICRO_ROS_AGENT_IP` is "10.0.0.11" and `CONFIG_MICRO_ROS_AGENT_PORT` is "8888" (both strings, and both configured via menuconfig)
- rmw_options is initialized by `rcl_init_options_get_rmw_init_options(&init_options)`;

**Comment by pablogs9** [comment]
@mmigliavacca please open another issues with steps for replicating the issue

**Comment by AntumArk** [comment]
Well, builing from source also failed... Got stuck at fastrtps. I guess I will try to set it up on my laptop then.

**Comment by AntumArk** [comment]
So I was able to run microros Agent on my laptop running ubuntu, and basic udp client on ESP32. So I can confirm that there was something off with windows firewall. 

As for building in32publisher on my laptop - I am having similar problem as https://github.com/micro-ROS/micro_ros_espidf_component/issues/60 . Investigating.

**Comment by AntumArk** [comment]
And the example finally works. 

So the HW setup now :

- Host PC runnning Ubuntu 20.04.4
- microros agent on host PC, started from  provided line in examples
- ESP32 running int32_publisher. 

1. Install espidf through [ESP-IDF install guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html)(i tried just using vscode extension but that just made more probelms, althogh at the end it started working)
2. clone [this repo](https://github.com/micro-ROS/micro_ros_espidf_component) into `/esp/esp-idf/components`
3. `cd /esp`
4. source idf
5. copy int32_example to `/esp/int32_example`
6. `cd /esp/int32_example`
7. `mkdir components`
8. `cd components`
9. `git clone https://github.com/micro-ROS/micro_ros_espidf_component`
10. `cd ..`
11. set target to esp32
12. `idf.py menuconfig`
13. `idf.py build` . for some reason at first i needed to press arrow keys when it was building wifi_provisioning . Otherwise it would just stay there
14. `idf.py flash`
15. `idf.py monitor`
16. In new terminal `docker run -it --rm --net=host microros/micro-ros-agent:galactic udp4 --port 8888 -v6`

And that is it. But I would still like to run this from my **Windows** environment because my laptop keeps powering off every 30 mins, so I will be investigating network issue. 

So for conclusion - check your firewall settings and try connecting to agent with basic UDP client. After that it should be able to start up. Although would it not be better if it would continue trying to reinitialize?
