### ISSUE TITLE
How can I add a existing ROS2 package to my esp project and use it?

### ISSUE THREAD

**Issue by zzMiao123** [micro-ROS/micro_ros_espidf_component#134]
- Hardware description: esp32
- RTOS: FreeRTOS
- Installation type: micro_ros_setup, robot_state_publisher
- Version or commit hash: foxy

#### Expected behavior
ESP32 runs a launch.py file of "robot_state_publisher" package in the app_main function.

#### Actual behavior
I dont know how to apply a package for my project.
clone the package into component folder, and then what to do?

#### Additional information
please let me know if there is any useful tutorial. Thank you very much!

**Comment by pablogs9** [comment]
Hi, you can add extra packages to the [extra packages folder](https://github.com/micro-ROS/micro_ros_espidf_component/tree/galactic/extra_packages), packages in this folder will be cross-compiled along with the micro-ROS stack and you will be able to run the in the MCU.

But those packages should be compatible with the MCU you are working on. I guess that by now a launch.py Python script won't work with micro-ROS. In any case, you can check the functionality of `robot_state_publisher` and replicate it using RCLC in micro-ROS.

Please reopen if you have more questions.

**Comment by zzMiao123** [comment]
Thanks, but without launch.py how can I "ros2 run <package>" in my MCU?

**Comment by pablogs9** [comment]
Please take a look at our [tutorials for RTOS](https://micro.ros.org/docs/tutorials/core/first_application_rtos/). micro-ROS do not have a CLI interface, it just provides a set of libraries to write ROS 2 compatible embedded code.

**Comment by zzMiao123** [comment]
OMG. Does that mean I cannot run executable files of packages in ROS2 community? I cannot use proven resources in ROS2 in my MCU for now, but only use rcl and rclc to create my program?
Sorry, I can't think of any other way to use the package's functions than to run the package directly.

**Comment by hellas2000** [comment]
I'm interested in your situation too, have you sucessfully done your job?
If not, I guess maybe you need to copy the code from that package and add it to your project, and start a new node in your code to perform the function of that package.
