### ISSUE TITLE
ESP32 can't find an included file during building of int32_publisher example

### ISSUE THREAD

**Issue by starcore2022** [micro-ROS/micro_ros_espidf_component#156]
**ESP32 can't find the included file of example project.**

- Hardware description: ESP32 serially linked to laptop through usb
- RTOS: FreeRTOS
- Installation type: micro_ros_espidf_component, ESP IDF master(latest)
- Version or commit hash: humble

**Steps to reproduce the issue**
My goal was to make a pcap about the communication, when running the int32_publisher example using embeddedRTPS and micro-ROS component.

 * Installed the ESP IDF master.
 * Copied in the micro_ros_espidf_component into the esp-idf/component directory.
 * Copied the example out to the esp folder and with cd command navigated into it.
 * Used the set-target command to set it up for using esp32.
 * Using the menuconfig command set micro-ROS to embeddedRTPS and set WiFi settings.
 * Then used the build command.

**Actual behavior**
![image](https://user-images.githubusercontent.com/110839026/183452191-83b3f951-1fce-4223-9077-aab5023e5c3f.png)

Complete output:

>  Executing action: all (aliases: build)
> Running ninja in directory /home/starcore/esp/int32_publisher/build
> Executing "ninja all"...
> [1/2] Re-running CMake...-- Component directory /home/starcore/Desktop does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Documents does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Downloads does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Music does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Pictures does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Public does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Templates does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/Videos does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/esp does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/microros_ws does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/snap does not contain a CMakeLists.txt file. No component will be added
> -- Component directory /home/starcore/teszt does not contain a CMakeLists.txt file. No component will be added
> -- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
> -- Building ESP-IDF components for target esp32
> -- Project sdkconfig file /home/starcore/esp/int32_publisher/sdkconfig
> Loading defaults file /home/starcore/esp/int32_publisher/sdkconfig.defaults...
> -- App "int32_publisher" version: 1
> -- Adding linker script /home/starcore/esp/int32_publisher/build/esp-idf/esp_system/ld/memory.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_system/ld/esp32/sections.ld.in
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.api.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/soc/esp32/ld/esp32.peripherals.ld
> -- Using embeddedRTPS middleware
> mkdir -p /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/micro_ros_src/libmicroros; cd /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/micro_ros_src/libmicroros; \
> for file in $(find /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/micro_ros_src/install/lib/ -name '*.a'); do \
> 	folder=$(echo $file | sed -E "s/(.+)\/(.+).a/\2/"); \
> 	mkdir -p $folder; cd $folder; /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ar x $file; \
> 	for f in *; do \
> 		mv $f ../$folder-$f; \
> 	done; \
> 	cd ..; rm -rf $folder; \
> done ; \
> /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-ar rc -s libmicroros.a *.obj; cp libmicroros.a /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble; \
> cd ..; rm -rf libmicroros; \
> cp -R /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/micro_ros_src/install/include /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/include;
> -- Components: app_trace app_update bootloader bootloader_support bt cmock console cxx driver efuse esp-tls esp_adc esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_psram esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_wifi espcoredump esptool_py fatfs freertos hal heap http_parser idf_test ieee802154 json log lwip main mbedtls micro_ros_espidf_component-humble mqtt newlib nvs_flash openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
> -- Component paths: /home/starcore/esp/esp-idf/components/app_trace /home/starcore/esp/esp-idf/components/app_update /home/starcore/esp/esp-idf/components/bootloader /home/starcore/esp/esp-idf/components/bootloader_support /home/starcore/esp/esp-idf/components/bt /home/starcore/esp/esp-idf/components/cmock /home/starcore/esp/esp-idf/components/console /home/starcore/esp/esp-idf/components/cxx /home/starcore/esp/esp-idf/components/driver /home/starcore/esp/esp-idf/components/efuse /home/starcore/esp/esp-idf/components/esp-tls /home/starcore/esp/esp-idf/components/esp_adc /home/starcore/esp/esp-idf/components/esp_common /home/starcore/esp/esp-idf/components/esp_eth /home/starcore/esp/esp-idf/components/esp_event /home/starcore/esp/esp-idf/components/esp_gdbstub /home/starcore/esp/esp-idf/components/esp_hid /home/starcore/esp/esp-idf/components/esp_http_client /home/starcore/esp/esp-idf/components/esp_http_server /home/starcore/esp/esp-idf/components/esp_https_ota /home/starcore/esp/esp-idf/components/esp_https_server /home/starcore/esp/esp-idf/components/esp_hw_support /home/starcore/esp/esp-idf/components/esp_lcd /home/starcore/esp/esp-idf/components/esp_local_ctrl /home/starcore/esp/esp-idf/components/esp_netif /home/starcore/esp/esp-idf/components/esp_phy /home/starcore/esp/esp-idf/components/esp_pm /home/starcore/esp/esp-idf/components/esp_psram /home/starcore/esp/esp-idf/components/esp_ringbuf /home/starcore/esp/esp-idf/components/esp_rom /home/starcore/esp/esp-idf/components/esp_serial_slave_link /home/starcore/esp/esp-idf/components/esp_system /home/starcore/esp/esp-idf/components/esp_timer /home/starcore/esp/esp-idf/components/esp_wifi /home/starcore/esp/esp-idf/components/espcoredump /home/starcore/esp/esp-idf/components/esptool_py /home/starcore/esp/esp-idf/components/fatfs /home/starcore/esp/esp-idf/components/freertos /home/starcore/esp/esp-idf/components/hal /home/starcore/esp/esp-idf/components/heap /home/starcore/esp/esp-idf/components/http_parser /home/starcore/esp/esp-idf/components/idf_test /home/starcore/esp/esp-idf/components/ieee802154 /home/starcore/esp/esp-idf/components/json /home/starcore/esp/esp-idf/components/log /home/starcore/esp/esp-idf/components/lwip /home/starcore/esp/int32_publisher/main /home/starcore/esp/esp-idf/components/mbedtls /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble /home/starcore/esp/esp-idf/components/mqtt /home/starcore/esp/esp-idf/components/newlib /home/starcore/esp/esp-idf/components/nvs_flash /home/starcore/esp/esp-idf/components/openthread /home/starcore/esp/esp-idf/components/partition_table /home/starcore/esp/esp-idf/components/perfmon /home/starcore/esp/esp-idf/components/protobuf-c /home/starcore/esp/esp-idf/components/protocomm /home/starcore/esp/esp-idf/components/pthread /home/starcore/esp/esp-idf/components/sdmmc /home/starcore/esp/esp-idf/components/soc /home/starcore/esp/esp-idf/components/spi_flash /home/starcore/esp/esp-idf/components/spiffs /home/starcore/esp/esp-idf/components/tcp_transport /home/starcore/esp/esp-idf/components/tinyusb /home/starcore/esp/esp-idf/components/ulp /home/starcore/esp/esp-idf/components/unity /home/starcore/esp/esp-idf/components/usb /home/starcore/esp/esp-idf/components/vfs /home/starcore/esp/esp-idf/components/wear_levelling /home/starcore/esp/esp-idf/components/wifi_provisioning /home/starcore/esp/esp-idf/components/wpa_supplicant /home/starcore/esp/esp-idf/components/xtensa
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/starcore/esp/int32_publisher/build
> [9/839] Generating ../../partition_table/partition-table.binPartition table binary generated. Contents:
> *******************************************************************************
> # ESP-IDF Partition Table
> # Name, Type, SubType, Offset, Size, Flags
> nvs,data,nvs,0x9000,24K,
> phy_init,data,phy,0xf000,4K,
> factory,app,factory,0x10000,1M,
> *******************************************************************************
> [319/839] Performing configure step for 'bootloader'-- Found Git: /usr/bin/git (found version "2.34.1") 
> -- The C compiler identification is GNU 11.2.0
> -- The CXX compiler identification is GNU 11.2.0
> -- The ASM compiler identification is GNU
> -- Found assembler: /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Building ESP-IDF components for target esp32
> -- Project sdkconfig file /home/starcore/esp/int32_publisher/sdkconfig
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of time_t
> -- Check size of time_t - done
> -- Adding linker script /home/starcore/esp/esp-idf/components/soc/esp32/ld/esp32.peripherals.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.api.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/bootloader/subproject/main/ld/esp32/bootloader.ld
> -- Adding linker script /home/starcore/esp/esp-idf/components/bootloader/subproject/main/ld/esp32/bootloader.rom.ld
> -- Components: bootloader bootloader_support efuse esp_common esp_hw_support esp_rom esp_system esptool_py freertos hal log main micro-ecc newlib partition_table soc spi_flash xtensa
> -- Component paths: /home/starcore/esp/esp-idf/components/bootloader /home/starcore/esp/esp-idf/components/bootloader_support /home/starcore/esp/esp-idf/components/efuse /home/starcore/esp/esp-idf/components/esp_common /home/starcore/esp/esp-idf/components/esp_hw_support /home/starcore/esp/esp-idf/components/esp_rom /home/starcore/esp/esp-idf/components/esp_system /home/starcore/esp/esp-idf/components/esptool_py /home/starcore/esp/esp-idf/components/freertos /home/starcore/esp/esp-idf/components/hal /home/starcore/esp/esp-idf/components/log /home/starcore/esp/esp-idf/components/bootloader/subproject/main /home/starcore/esp/esp-idf/components/bootloader/subproject/components/micro-ecc /home/starcore/esp/esp-idf/components/newlib /home/starcore/esp/esp-idf/components/partition_table /home/starcore/esp/esp-idf/components/soc /home/starcore/esp/esp-idf/components/spi_flash /home/starcore/esp/esp-idf/components/xtensa
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/starcore/esp/int32_publisher/build/bootloader
> [99/100] Generating binary image from built executableesptool.py v4.2
> Creating esp32 image...
> Merged 1 ELF section
> Successfully created esp32 image.
> Generated /home/starcore/esp/int32_publisher/build/bootloader/bootloader.bin
> [100/100] cd /home/starcore/esp/int32_publisher/b...p/int32_publisher/build/bootloader/bootloader.binBootloader binary size 0x66d0 bytes. 0x930 bytes (8%) free.
> [797/839] Building C object esp-idf/micro_ros_esp....dir/network_interfaces/uros_ethernet_netif.c.objFAILED: esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_ethernet_netif.c.obj 
> /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc  -I/home/starcore/esp/int32_publisher/build/config -I/home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/network_interfaces -I/home/starcore/esp/esp-idf/components/newlib/platform_include -I/home/starcore/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/starcore/esp/esp-idf/components/freertos/esp_additions/include/freertos -I/home/starcore/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/starcore/esp/esp-idf/components/freertos/esp_additions/include -I/home/starcore/esp/esp-idf/components/esp_hw_support/include -I/home/starcore/esp/esp-idf/components/esp_hw_support/include/soc -I/home/starcore/esp/esp-idf/components/esp_hw_support/include/soc/esp32 -I/home/starcore/esp/esp-idf/components/esp_hw_support/port/esp32/. -I/home/starcore/esp/esp-idf/components/esp_hw_support/port/esp32/private_include -I/home/starcore/esp/esp-idf/components/heap/include -I/home/starcore/esp/esp-idf/components/log/include -I/home/starcore/esp/esp-idf/components/soc/include -I/home/starcore/esp/esp-idf/components/soc/esp32/. -I/home/starcore/esp/esp-idf/components/soc/esp32/include -I/home/starcore/esp/esp-idf/components/hal/esp32/include -I/home/starcore/esp/esp-idf/components/hal/include -I/home/starcore/esp/esp-idf/components/hal/platform_port/include -I/home/starcore/esp/esp-idf/components/esp_rom/include -I/home/starcore/esp/esp-idf/components/esp_rom/include/esp32 -I/home/starcore/esp/esp-idf/components/esp_rom/esp32 -I/home/starcore/esp/esp-idf/components/esp_common/include -I/home/starcore/esp/esp-idf/components/esp_system/include -I/home/starcore/esp/esp-idf/components/esp_system/port/soc -I/home/starcore/esp/esp-idf/components/esp_system/port/include/private -I/home/starcore/esp/esp-idf/components/xtensa/include -I/home/starcore/esp/esp-idf/components/xtensa/esp32/include -I/home/starcore/esp/esp-idf/components/lwip/include -I/home/starcore/esp/esp-idf/components/lwip/include/apps -I/home/starcore/esp/esp-idf/components/lwip/include/apps/sntp -I/home/starcore/esp/esp-idf/components/lwip/lwip/src/include -I/home/starcore/esp/esp-idf/components/lwip/port/esp32/include -I/home/starcore/esp/esp-idf/components/lwip/port/esp32/include/arch -I/home/starcore/esp/esp-idf/components/nvs_flash/include -I/home/starcore/esp/esp-idf/components/spi_flash/include -mlongcalls -Wno-frame-address  -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/home/starcore/esp/int32_publisher=. -fmacro-prefix-map=/home/starcore/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0-dev-4723-g30e8f19f5a\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_ethernet_netif.c.obj -MF esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_ethernet_netif.c.obj.d -o esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_ethernet_netif.c.obj -c /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/network_interfaces/uros_ethernet_netif.c
> /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/network_interfaces/uros_ethernet_netif.c:5:10: fatal error: esp_netif.h: No such file or directory
>     5 | #include "esp_netif.h"
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> [798/839] Building C object esp-idf/micro_ros_esp...mble.dir/network_interfaces/uros_wlan_netif.c.objFAILED: esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_wlan_netif.c.obj 
> /home/starcore/.espressif/tools/xtensa-esp32-elf/esp-2022r1-RC1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc  -I/home/starcore/esp/int32_publisher/build/config -I/home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/network_interfaces -I/home/starcore/esp/esp-idf/components/newlib/platform_include -I/home/starcore/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/starcore/esp/esp-idf/components/freertos/esp_additions/include/freertos -I/home/starcore/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/starcore/esp/esp-idf/components/freertos/esp_additions/include -I/home/starcore/esp/esp-idf/components/esp_hw_support/include -I/home/starcore/esp/esp-idf/components/esp_hw_support/include/soc -I/home/starcore/esp/esp-idf/components/esp_hw_support/include/soc/esp32 -I/home/starcore/esp/esp-idf/components/esp_hw_support/port/esp32/. -I/home/starcore/esp/esp-idf/components/esp_hw_support/port/esp32/private_include -I/home/starcore/esp/esp-idf/components/heap/include -I/home/starcore/esp/esp-idf/components/log/include -I/home/starcore/esp/esp-idf/components/soc/include -I/home/starcore/esp/esp-idf/components/soc/esp32/. -I/home/starcore/esp/esp-idf/components/soc/esp32/include -I/home/starcore/esp/esp-idf/components/hal/esp32/include -I/home/starcore/esp/esp-idf/components/hal/include -I/home/starcore/esp/esp-idf/components/hal/platform_port/include -I/home/starcore/esp/esp-idf/components/esp_rom/include -I/home/starcore/esp/esp-idf/components/esp_rom/include/esp32 -I/home/starcore/esp/esp-idf/components/esp_rom/esp32 -I/home/starcore/esp/esp-idf/components/esp_common/include -I/home/starcore/esp/esp-idf/components/esp_system/include -I/home/starcore/esp/esp-idf/components/esp_system/port/soc -I/home/starcore/esp/esp-idf/components/esp_system/port/include/private -I/home/starcore/esp/esp-idf/components/xtensa/include -I/home/starcore/esp/esp-idf/components/xtensa/esp32/include -I/home/starcore/esp/esp-idf/components/lwip/include -I/home/starcore/esp/esp-idf/components/lwip/include/apps -I/home/starcore/esp/esp-idf/components/lwip/include/apps/sntp -I/home/starcore/esp/esp-idf/components/lwip/lwip/src/include -I/home/starcore/esp/esp-idf/components/lwip/port/esp32/include -I/home/starcore/esp/esp-idf/components/lwip/port/esp32/include/arch -I/home/starcore/esp/esp-idf/components/nvs_flash/include -I/home/starcore/esp/esp-idf/components/spi_flash/include -mlongcalls -Wno-frame-address  -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/home/starcore/esp/int32_publisher=. -fmacro-prefix-map=/home/starcore/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0-dev-4723-g30e8f19f5a\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_wlan_netif.c.obj -MF esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_wlan_netif.c.obj.d -o esp-idf/micro_ros_espidf_component-humble/CMakeFiles/__idf_micro_ros_espidf_component-humble.dir/network_interfaces/uros_wlan_netif.c.obj -c /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/network_interfaces/uros_wlan_netif.c
> /home/starcore/esp/esp-idf/components/micro_ros_espidf_component-humble/network_interfaces/uros_wlan_netif.c:7:10: fatal error: esp_wifi.h: No such file or directory
>     7 | #include "esp_wifi.h"
>       |          ^~~~~~~~~~~~
> compilation terminated.
> [802/839] Building C object esp-idf/json/CMakeFiles/__idf_json.dir/cJSON/cJSON.c.objninja: build stopped: subcommand failed.
> HINT: Please check if you've specified all component dependencies with 'idf_component_register(REQUIRES ...)'. If the component is not present then it should be added by the IDF Component Manager. For more information run 'idf.py docs -sp api-guides/build-system.html'.
> ninja failed with exit code 1, output of the command is in the /home/starcore/esp/int32_publisher/build/log/idf_py_stderr_output_101849 and /home/starcore/esp/int32_publisher/build/log/idf_py_stdout_output_101849
> 

**Additional information**
Modified nothing else and installed the dependencies.

**Comment by pablogs9** [comment]
Does this work if you create a component directory in your project and use `EXTRA_COMPONENT_DIRS` CMake variable?

**Comment by starcore2022** [comment]
If I use that the problem remains the same, but if i move the conents of the "micro_ros_espidf_component-humble" folder out and delete the folder, then throws error, for not finding this forlder.
![image](https://user-images.githubusercontent.com/110839026/183583561-200bbfbb-51bf-4b0c-b9ed-af173194942c.png)

**Comment by starcore2022** [comment]
Changed things around, now I removed the **"micro_ros_espidf_component-humble"** folder, from the component folder of esp-idf, because it started clashing with the **EXTRA_COMPONENT_DIRS** setting, now gets trough the the **"#include esp_wifi.h"**, but stops at the "#include rcl/rcl.h" line.
![image](https://user-images.githubusercontent.com/110839026/183587394-fb2da822-d44e-4b08-a8c9-e89af7fea89a.png)

**Comment by pablogs9** [comment]
Remove the "humble" from the folder name: `micro_ros_espidf_component`

**Comment by starcore2022** [comment]
Removed and redid the set-target and build:
![image](https://user-images.githubusercontent.com/110839026/183589993-bbf6f0d2-0fb3-420d-a8bc-15172db8455b.png)

**Comment by starcore2022** [comment]
If I source the ROS2 and micro-ROS setup, then it stops at the **"esp_wifi.h"**:
![image](https://user-images.githubusercontent.com/110839026/183593703-9406a206-cbcb-46aa-b764-e7cc22a30f92.png)

**Comment by starcore2022** [comment]
If I do this in a new terminal without sourcing any ROS2 or micro-ROS setup:
![image](https://user-images.githubusercontent.com/110839026/183595350-9a4fc6e4-3a69-4c23-9bd2-ef3011a300c6.png)

**Comment by starcore2022** [comment]
I deleted the ESP IDF and reinstalled the 4.4 version, after redoing the same steps: 
![image](https://user-images.githubusercontent.com/110839026/183603194-1122125f-316e-4813-8fbf-0f908e3290ba.png)

**Comment by starcore2022** [comment]
I redid it with the 4.3 version and gives the same error as with the 4.4 version.

**Comment by pablogs9** [comment]
Does it works if you follow [the instructions](https://github.com/micro-ROS/micro_ros_espidf_component#example)?

**Comment by starcore2022** [comment]
Tried, but the same error remains:
![image](https://user-images.githubusercontent.com/110839026/183608555-cc69fcee-bd0b-48ce-81a0-484163af10c4.png)

**Comment by pablogs9** [comment]
Please retry in a clean environment and follow the instructions because CI is passing https://github.com/micro-ROS/micro_ros_espidf_component/actions/runs/2822730553

**Comment by starcore2022** [comment]
Deleted the esp folder, where I installed the ESP IDF and now I tried with the esp-idf folder included in the micro-ROS I installed at the microros_ws workspace and redoing as the instructions:
![image](https://user-images.githubusercontent.com/110839026/183613776-059a5006-ccd2-4276-8175-7cce01e64bb5.png)

**Comment by pablogs9** [comment]
Provide replicable steps in a clean environment

**Comment by starcore2022** [comment]
Thank you for the help, after a lot of clean up and retry finally managed to complete building process with the latest stable (4.4.2) version and placing the int32_publisher project into the examples folder as well as manually creating and cloning in the micro-ROS component into the components folder.
