### ISSUE TITLE
multithread_publisher with custom_transport 

### ISSUE THREAD

**Issue by shecker** [micro-ROS/micro_ros_espidf_component#157]
Hello,

I would like to use the multithreaded publisher example with custom_transport via a usb cable. We are using the latest foxy branch.

Unfortunately I get a continuous reconnection on the host side with the publishers being created but then the client getting deleted. 

Does anyone know what the issue may be?
Thanks 
![Screenshot from 2022-08-17 08-49-44](https://user-images.githubusercontent.com/1975743/185053448-220a8e4e-058a-4f3e-8130-6ef140fafb29.png)

**Comment by Acuadros95** [comment]
Hi @shecker, a few questions:

- Did you modify the example in any way? (I see three publishers are created instead of two as in the example).
- Does your code works with the default UDP or the provided serial transport?
- Could you elaborate on how your custom transport works?

**Comment by Acuadros95** [comment]
> I believe the issue occurs when I change this line from ON to OFF:
`"-DUCLIENT_PROFILE_MULTITHREAD=ON"`

That is expected, this option enables micro-ROS multithread support.
**It needs to be enabled for any multithreaded app.**
