### ISSUE TITLE
Unable to receive data at subscriber using Micro ROS with embedded RTPS mode with two ESP32 Publisher & Subscriber 

### ISSUE THREAD

**Issue by ManvithRaj** [micro-ROS/micro_ros_espidf_component#164]
Hi @pablogs9 

I went through this component and also embedded working group meeting related Embedded RTPS demo you have shown.

I tried this micro ros component building with Embedded RTPS  for both subscriber and publisher with two ESP32 Devices but problem is My publisher ESP32 publishing the data and My Subscriber ESP32 not receiving it both are connected to same wifi-router.

Could you please help me here if I am missing anything or any configuration updated related to IP and Ports etc. 

I am thinking that this communication will happen through by joining a IGMP Group with LWIP  Where i could see that it is joining into group 239.255.0.1  but still there is no communication between them.

I have used same topic name for subscriber and publisher but still no luck.

Kindly please help in this. I am struggling with this issue from many days and also I am not less aware of underlying micro ROS , LWIP and RTPS components.

Thank you in advance.

**Comment by pablogs9** [comment]
Hello, we are not providing active support on this feature because this middleware is experimentally integrated into micro-ROS.  Maybe you can find more information and answers in the official repo of the middleware: https://github.com/embedded-software-laboratory/embeddedRTPS
