### ISSUE TITLE
Subscriber Call Back Not happening when 2 tasks running with Embedded RTPS

### ISSUE THREAD

**Issue by ManvithRaj** [micro-ROS/micro_ros_espidf_component#168]
> You cannot init micro-ROS twice.
> 
> The recommended approach is:
> 
> * to init micro-ROS in one task,
> * create two executors one for the timer and the other for the subscription
> * spin the executors in separate tasks and callbacks will execute in each task
> * ensure that both executors have mutual exclusion or try to enable [UCLIENT_PROFILE_MULTITHREAD](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/CMakeLists.txt#L67) (nor sure if it will work out of the box with this component)

Hi @pablogs9 

I tried above steps first 3 points. 4th point i could not find in EmbeddedRTPS . publisher is publishing the data but subscriber call back is not happening.

Here is my restructured main.c code . could you please verify once and please help in why subscriber callback is not happening. any special condition do I need to meet ?

#include <string.h>
#include <stdio.h>
#include <unistd.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_system.h"

#include <uros_network_interfaces.h>
#include <rcl/rcl.h>
#include <rcl/error_handling.h>
#include <std_msgs/msg/string.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include "sntp_example_main.h"

//#include <WiFi.h>
#include "time.h"

#define RCCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){printf("Failed status on line %d: %d. Aborting.\n",__LINE__,(int)temp_rc);vTaskDelete(NULL);}}
#define RCSOFTCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){printf("Failed status on line %d: %d. Continuing.\n",__LINE__,(int)temp_rc);}}

rcl_publisher_t publisher;
rcl_subscription_t subscriber;
std_msgs__msg__String msg;
std_msgs__msg__String msg2;

time_t now;
struct tm timeinfo;

uint32_t t_sec;
uint32_t t_usec;
uint32_t t_msec;

uint32_t counter = 0;
#define ARRAY_LEN 200

rclc_executor_t executor;
rclc_executor_t executor2;
   
void subscription_callback(const void * msgin)
{
	const std_msgs__msg__String * msg = (const std_msgs__msg__String *)msgin;
	//time(&now);
	//example_sntp_get_system_time(&t_sec,&t_usec);
	//printf("Received: %s @ time : %ld  ,sec: %d , usec:%d \n", msg->data.data,now ,t_sec,t_usec);
	printf("Received: %s \n", msg->data.data);
}

void timer_callback(rcl_timer_t * timer, int64_t last_call_time)
{
        
    //time(&now);
    //example_sntp_get_system_time(&t_sec,&t_usec);
	if (timer != NULL) {
	       sprintf(msg.data.data, "Hello from micro-ROS #%d", counter++);
		msg.data.size = strlen(msg.data.data);
		RCSOFTCHECK(rcl_publish(&publisher, &msg, NULL));
		//printf("Publishing: %s @ time: %ld ,sec: %d , msec:%d \n", msg.data.data,now,t_sec,t_msec);
		printf("Publishing: %s \n", msg.data.data);
	}
}

void micro_ros_task(void * arg)
{
       printf("initializing init task.....\n");
       //vTaskDelay(1000);
	rcl_allocator_t allocator = rcl_get_default_allocator();
	rclc_support_t support;

	rcl_init_options_t init_options = rcl_get_zero_initialized_init_options();
	RCCHECK(rcl_init_options_init(&init_options, allocator));

	// create init_options
	RCCHECK(rclc_support_init_with_options(&support, 0, NULL, &init_options, &allocator));

	// create node
	rcl_node_t node;
	RCCHECK(rclc_node_init_default(&node, "esp32_int32_publisher", "", &support));
	
	// create subscriber
	RCCHECK(rclc_subscription_init_default(
		&subscriber,
		&node,
		ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String),
		"freertos_int32_publisher"));
		
      // create executor
	executor2 = rclc_executor_get_zero_initialized_executor();
	RCCHECK(rclc_executor_init(&executor2, &support.context, 1, &allocator));
	RCCHECK(rclc_executor_add_subscription(&executor2, &subscriber, &msg2, &subscription_callback, ON_NEW_DATA));

	// create publisher
	RCCHECK(rclc_publisher_init_default(
		&publisher,
		&node,
		ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, String),
		"freertos_int32_publisher"));
        // create node2
	//rcl_node_t node2;
	//RCCHECK(rclc_node_init_default(&node2, "int32_subscriber_rclc", "", &support));

	// create timer,
	rcl_timer_t timer;
	const unsigned int timer_timeout = 1000;
	RCCHECK(rclc_timer_init_default(
		&timer,
		&support,
		RCL_MS_TO_NS(timer_timeout),
		timer_callback));

	// create publisher executor

	RCCHECK(rclc_executor_init(&executor, &support.context, 1, &allocator));
	RCCHECK(rclc_executor_add_timer(&executor, &timer));
	
       
	
	
	// Fill the array with a known sequence
	msg.data.data = (char * ) malloc(ARRAY_LEN * sizeof(char));
	msg.data.size = 0;
	msg.data.capacity = ARRAY_LEN;
	
        msg2.data.data = (char * ) malloc(ARRAY_LEN * sizeof(char));
	msg2.data.size = 0;
	msg2.data.capacity = ARRAY_LEN;

	//msg.data = 0;
	 //init and get the time
  	////configTime(gmtOffset_sec, daylightOffset_sec, ntpServer);
  	//printLocalTime();

	while(1){
	       printf("init task running \n");
		//rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100));
		//usleep(10000);
		vTaskDelay(1000);
	}

	// free resources
	//RCCHECK(rcl_publisher_fini(&publisher, &node));
	//RCCHECK(rcl_node_fini(&node));
        printf("init task deleted \n");
  	vTaskDelete(NULL);
}

void micro_ros_task_pub(void * arg)
{
       vTaskDelay(2000);
	printf("initializing publisher task.....\n");	
        

	 while(1){
	        //printf("publisher task running \n");
                rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100));
                //usleep(100000);
                vTaskDelay(100);
        }

  	//rclc_executor_spin(&executor);

	//RCCHECK(rcl_subscription_fini(&subscriber, &node));
	//RCCHECK(rcl_node_fini(&node));
	printf("publisher task deleted \n");
	vTaskDelete(NULL);
}

void micro_ros_task_sub(void * arg)
{
        vTaskDelay(1000);
	printf("initializing sbscriber task.....\n");	

	 while(1){
	       //  printf("subscriber task running \n");
                rclc_executor_spin_some(&executor2, RCL_MS_TO_NS(100));
                usleep(100000);
                vTaskDelay(100);
        }

  	//rclc_executor_spin(&executor);

	//RCCHECK(rcl_subscription_fini(&subscriber, &node));
	//RCCHECK(rcl_node_fini(&node));
	printf("subscriber task deleted \n");
	vTaskDelete(NULL);
}

void app_main(void)
{
#if defined(CONFIG_MICRO_ROS_ESP_NETIF_WLAN) || defined(CONFIG_MICRO_ROS_ESP_NETIF_ENET)
    ESP_ERROR_CHECK(uros_network_interface_initialize());
#endif
    //time_t now;
    //struct tm timeinfo;
    //time(&now);
    //localtime_r(&now, &timeinfo);
    // Is time set? If not, tm_year will be (1970 - 1900).
    //if (timeinfo.tm_year < (2016 - 1900)) {

     //   printf("obtaining time \n");
     //   obtain_time();
        // update 'now' variable with current time
     //   time(&now);

    //}
    //printf("CUrrent time is %ld" ,now);
    xTaskCreate(micro_ros_task,
            "uros_task",
            CONFIG_MICRO_ROS_APP_STACK,
            NULL,
            CONFIG_MICRO_ROS_APP_TASK_PRIO,
            NULL);
    xTaskCreate(micro_ros_task_pub,
            "uros_task",
            CONFIG_MICRO_ROS_APP_STACK,
            NULL,
            CONFIG_MICRO_ROS_APP_TASK_PRIO,
            NULL);
    xTaskCreate(micro_ros_task_sub,
            "uros_task",
            CONFIG_MICRO_ROS_APP_STACK,
            NULL,
            CONFIG_MICRO_ROS_APP_TASK_PRIO,
            NULL);
       
}

_Originally posted by @ManvithRaj in https://github.com/micro-ROS/micro_ros_espidf_component/issues/167#issuecomment-1339240157_

**Comment by pablogs9** [comment]
Hello we do not provide support for Embedded RTPS since it is an experimental middleware integration in micro-ROS. Please refer to the official repo for questions and issues: https://github.com/embedded-software-laboratory/embeddedRTPS
