### ISSUE TITLE
addtwoints_server example linking issues with Embedded RTPS as Middleware 

### ISSUE THREAD

**Issue by ManvithRaj** [micro-ROS/micro_ros_espidf_component#171]
Hi @pablogs9 ,

I am trying to build given example **addtwoints_server** by choosing EmbeddedRTPS as Micro-ROS Middleware.

Getting Linking issues at **rmw_service_response_publisher_get_actual_qos** as undefined reference as below

![image](https://user-images.githubusercontent.com/117094438/209791685-20e4a702-c377-4988-937a-3ec3871285f2.png)

i could see this function XRCE Middleware but not in embedded RTPS.

Please help on this.

and also I have queries like
1. Does this Request Response method works without agent with this embedded RTPS Approach ?
2. Is there any way to make this work without agent if embeddedRTPS Apporach doent work for this request response method ?

Thank you in advance

**Comment by Acuadros95** [comment]
> Does this Request Response method works without agent with this embedded RTPS Approach ?

EmbeddedRTPS does not support services and its not in our roadmap to add that functionality.

> Is there any way to make this work without agent if embeddedRTPS Apporach doent work for this request response method ?

Not at this moment.
