### ISSUE TITLE
Small question regarding the microROS agent.

### ISSUE THREAD

**Issue by Ncouch64** [micro-ROS/micro_ros_espidf_component#241]
I apologize if I should not be posting this here but I just had a small question about the microROS agent which is why I am not using the issue template. I see that the microROS agent is done through a docker container and I have been able to do the int32_publisher demo just fine after some network troubleshooting.

My question is if there is a way to run the microROS agent on a host machine without using docker. I am potentially looking to use a resource constrained machine to act as a host and running docker in this setup may not be feasible. Thanks for the assistance!

**Comment by pablogs9** [comment]
You can use the .deb distribution of Vulcanexus: https://docs.vulcanexus.org/en/latest/rst/installation/linux_binary_installation.html

**Comment by Ncouch64** [comment]
> You can use the .deb distribution of Vulcanexus: https://docs.vulcanexus.org/en/latest/rst/installation/linux_binary_installation.html

Just wanted to throw a little update here, I just finished the full process of getting vulcannexus built on my system and a microROS agent running, without docker, and it does in fact properly receive info from the esp32 publisher example. You have my thanks! This can probably be marked as completed!
