### ISSUE TITLE
How can I configure Security QoS?

### ISSUE THREAD

**Issue by YiJunKo** [micro-ROS/micro_ros_espidf_component#245]
## How can I configure Security QoS?

- Hardware description: ESP32-S3-EYE
- RTOS: FreeRTOS
- Installation type: micro_ros_setup
- Version or commit hash: foxy

#### Steps to reproduce the issue
I would like to know how to set up my security QoS on micro-ROS (that is, on the XRCE-DDS client). Since there is currently no manual available, I am unsure how to implement it.

**Comment by pablogs9** [comment]
Hello @YiJunKo, micro-ROS does not support DDS Security.

**Comment by YiJunKo** [comment]
Hello @pablogs9  , thanks your answers!
I would also like to ask where I can find the list of QoS supported by micro-ROS？

**Comment by pablogs9** [comment]
You can take a look at the middleware configuration here: https://micro-xrce-dds.docs.eprosima.com/en/latest/

**Comment by YiJunKo** [comment]
Hi @pablogs9 , 
I have referred to the following: https://micro.ros.org/docs/tutorials/advanced/microxrcedds_rmw_configuration/ and also looked at the colcon.meta of this project. If I am developing and flashing using this project, are the only available QoS options as follows?
"rmw_microxrcedds": {
            "cmake-args": [
                "-DRMW_UXRCE_XML_BUFFER_LENGTH=400",
                "-DRMW_UXRCE_TRANSPORT=udp",
                "-DRMW_UXRCE_MAX_NODES=1",
                "-DRMW_UXRCE_MAX_PUBLISHERS=2",
                "-DRMW_UXRCE_MAX_SUBSCRIPTIONS=2",
                "-DRMW_UXRCE_MAX_SERVICES=1",
                "-DRMW_UXRCE_MAX_CLIENTS=1",
                "-DRMW_UXRCE_MAX_HISTORY=1"
            ]
        },

**Comment by pablogs9** [comment]
Those are not QoS, those are middleware configuration parameters, please take a look at micro-ROS documentation: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/memory_management/memory_management.html
