### ISSUE TITLE
Failed on compile 'FAILED: libmicroros-prefix...

### ISSUE THREAD

**Issue by wegunterjr** [micro-ROS/micro_ros_espidf_component#70]
## Issue template

- Hardware description: esp32s2
- RTOS:FreeRTOS
- Installation type: idf.py build 
- Version or commit hash:  foxy

#### Steps to reproduce the issue
Clone micro_ros_espidf_component into components folder
idf.py menuconfig - set MicroRos menu parameters
idf.py build

#### Expected behavior
Successful build so I can flash

#### Actual behavior

FAILED: libmicroros-prefix/src/libmicroros_project-stamp/libmicroros_project-build ../components/micro_ros_espidf_component/libmicroros.a

**Comment by pablogs9** [comment]
Which version of ESP-IDF are you using?

**Comment by wegunterjr** [comment]
4.2, but I think the problem was that I was doing this on windows os.  I didn't even think about it til well into the day that I wasn't on linux OS, and didn't have make tools installed... shmaybe?
