### ISSUE TITLE
Porting ros1 spotmicro code to microros esp32 - help installing tf2_ package

### ISSUE THREAD

**Issue by antonioasaro** [micro-ROS/micro_ros_espidf_component#98]
## Issue template

- Hardware description:  esp32
- RTOS:  freertos
- Installation type:  espidf 4.3
- Version or commit hash:  galatic

I'm trying to port Mike's sportmicro code from ros1 to microros.
Mike's code includes references to tf2 - see below
https://github.com/mike4192/spotMicro

```
#include "tf2/LinearMath/Quaternion.h"
#include "tf2_eigen/tf2_eigen.h"
#include "tf2_geometry_msgs/tf2_geometry_msgs.h"

....

  TransformStamped tr_stamped;

  // base_link to front_link transform
  tr_stamped = createTransform("base_link", "front_link",
                               0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0);
```

The include files aren't found.
So I tried cloning ros2/geometry2 to micro_ros_espidf_component/micro_ros_src/src.
The make -f libmicroros.mk compile failed miserably.
I tried putting ros2/geometry2 in the extra package directory - that didn't work either.
I noticed references to microros/geometry2 github repositories on the internet (as if there's a special microros version of geometry2)
Unfortunately, all links I searched were broken.
Looking for any help I can get.
Is this even possible?

**Comment by pablogs9** [comment]
Hello, AFAIK there is no active development right now for any embedded TF library. Regarding porting the existing ros2/geometry to micro-ROS, it may be non-trivial. Probably the easiest part should be to use the existing types by adding them to the [extra packages folder](https://github.com/micro-ROS/micro_ros_espidf_component/tree/galactic/extra_packages).


CC: @ralph-lange @JanStaschulat
